version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25062002
      POSTGRES_DB: UnderSounds
    ports:
      - "5555:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: undersounds-backend:v1
    container_name: backend_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:25062002@db:5432/UnderSounds
      BASE_URL: "http://localhost:8888/static/"
      BASE_URL_2: "http://localhost:8888/"

    volumes:
      - ./backend:/app
    ports:
      - "8888:8000"
    restart: always

  frontend:
    build: ./proyecto
    image: undersounds-frontend:v1
    container_name: frontend_app
    # volumes:
    #   - ./proyecto:/app
    ports:
      - "4300:4200"
    command: npm run start:docker

    depends_on:
      - backend
    restart: always

volumes:
  pgdata: